export const depts_villes = [
    'ARIEGE-PAMIERS',
    'ARIEGE-FOIX',
    'ARIEGE-MIREPOIX',
    'ARIEGE-MAZERES',
    'AUDE-NARBONNE',
    'AUDE-CARCASSONNE',
    'AUDE-CASTELNAUDARY',
    'HAUTE GARONNE-TOULOUSE',
    'HAUTE GARONNE-COLOMIERS',
    'HAUTE GARONNE-TOURNEFEUILLE',
    'HAUTE GARONNE-MURET',
    'HAUTE GARONNE-BLAGNAC'
];

